module Addresses
    ( spaceOrStop
    , spaceOrStop'
    , spaceOrComma
    , spaceOrComma'
    , skipUntil
    , takeUntil
    , cardinalPoints
    , states
    , streetTypes
    , aPoint
    , aState
    , aStreetType
    , postcodeEOF
    , postcodeS
    , postcode
    , foundPoint
    , the
    , skipUntilN
    , takeUntilN

    , Suffix
    , Prefix
    , Number
    , Single
    , StreetNumber
    , singleNumber
    , singleFix
    , single
    , oneNumber
    , rangeNumber
    , streetNumber

    , Bag(..)
    , Box(..)
    , StreetName(..)
    , StreetType(..)
    , Pobox(..)
    , StreetAddress(..)
    , AddressLocation(..)
    , AuAddress(..)
    , addressLocation
    , step
    , poBox
    , bag
    , streetAddress
    , auAddress

    , Suburb(..)
    , State(..)
    , Postcode(..)
    , Locality(..)
    , locality
    ) where

import           Address
import           Components
import           Locality
import           StreetNumber
