module Addresses
    ( spaceOrStop
    , spaceOrStop'
    , spaceOrComma
    , spaceOrComma'
    , skipUntil
    , takeUntil
    , cardinalPoints
    , states
    , streetTypes
    , aPoint
    , aState
    , aStreetType
    , postcodeEOF
    , postcodeS
    , postcode
    , foundPoint
    , the
    , skipUntilN
    , takeUntilN

    , Suffix
    , Prefix
    , Number
    , Single
    , StreetNumber
    , singleNumber
    , singleFix
    , single
    , oneNumber
    , rangeNumber
    , streetNumber

    , Box
    , StreetName
    , StreetType
    , City
    , Postcode
    , State
    , Pobox(..)
    , StreetAddress
    , AddressLocation(..)
    , Address
    , addressLocation
    , step
    , poBox
    , streetAddress
    ) where

import           Address
import           Components
import           StreetNumber
